[constants]
t_max=20.0
dt=0.004
domain_size=[51.2, 38.4]
n_voxels=[1, 1]
rng_seed=0
cutoff=6.66
n_vertices=8
displacement_error = 0.5

[parameters]
radius = { min = 0.003, max=1.0, initial=0.5, individual=false }
# radius = 0.48
rigidity = 16.6
spring_tension = 15.0
damping = { min=0.0, max=75.0, initial=12.5 }
# damping = 8.0
strength = { min=0.0, max=2.0, initial=0.3 }
# strength = 0.4
growth_rate = { min=0.0, max=0.08, initial=0.016, individual=true }

[parameters.potential_type.Mie]
en = { min=0.1, max=10.0, initial=0.94}
em = { min=0.1, max=10.0, initial=0.22}
# em = 2.1
bound = 2.0

# [optimization.lhs_nelder_mead]
# max_iter = 3000

# [optimization.lhs_nelder_mead.latin_hypercube]
# n_points = 10_000
# n_steps = 3
# relative_reduction = 1.0

[optimization.differential_evolution]
seed = 0
max_iter = 400
pop_size = 40
recombination = 0.5
polish = true
